### ISSUE TITLE
The purpose of SimpleBatchNorm2d(1d)

### ISSUE THREAD

**Issue by mingkai-zheng** [zengarden/momentum2-teacher#1]
I really like this amazing work, but I'm wondering what is the purpose of the SimpleBatchNorm in your code.

**Comment by zengarden** [comment]
I'm glad you like this work. This is a modification left over from another previous exploration. The result should be no different from the original BN.

**Comment by mingkai-zheng** [comment]
Thank you so much for your reply, but I have another question about the normalization in contrastive learning, Since the bn will cause the information leaking of the intra-batch communication, have you ever tried using group normalization + weight standardization (The tricks used in Big Transfer (BiT) ) to replace bn?

**Comment by zengarden** [comment]
It should be possible to use this functional-based norm, refer to [BYOL works even without batch statistics](https://arxiv.org/pdf/2010.10241v1.pdf).
While BN of a large batch usually gets slightly better performances once we prevent information leaking, and you can refer to the BN of supervised field.  Besides, BN is convenient for downstream task comparison and has a lower inference cost.   All in all, I think both are ok.

**Comment by mingkai-zheng** [comment]
One more question, (I'm sorry to have so many questions lol).....    I noticed that for the MoCo variant, you simply set alpha int Momentum BN to 0.064 right? Have you ever tried to run MoCo with alpha 1 -> 0 (just like what you did in table 6), and how was the performance?

**Comment by zengarden** [comment]
I have not tried to use dynamic momentum param in BN when training MoCo. Just follow the practice of fixing momentum coefficient~(applied on weights) in MoCo,  here I also fix the BN momentum.  Unfortunately, I haven't done many experiments on this exploration.

**Comment by Hzzone** [comment]
@zengarden I have another question: Have you tried shuffling BN in MoCo against momentum BN? Can it help the training on ImageNet of BYOL? I have only used it on CIFAR-* which works well also without sync BN.  

Looking forward to your reply.

**Comment by zengarden** [comment]
> @zengarden I have another question: Have you tried shuffling BN in MoCo against momentum BN? Can it help the training on ImageNet of BYOL? I have only used it on CIFAR-* which works well also without sync BN.
> 
> Looking forward to your reply.

I haven't tried shuffling-BN on BYOL. I believe that the effects of shuffling-BN and sync-BN are the same, since the shuffling-BN can be regarded as a sampling version of sync-BN. The thing is shuffling/sync-BN involves extra communication across the devices, thus I recommend to use MomentumBN.

**Comment by Hzzone** [comment]
> > @zengarden I have another question: Have you tried shuffling BN in MoCo against momentum BN? Can it help the training on ImageNet of BYOL? I have only used it on CIFAR-* which works well also without sync BN.
> > Looking forward to your reply.
> 
> I haven't tried shuffling-BN on BYOL. I believe that the effects of shuffling-BN and sync-BN are the same, since the shuffling-BN can be regarded as a sampling version of sync-BN. The thing is shuffling/sync-BN involves extra communication across the devices, thus I recommend to use MomentumBN.

Thanks for your reply. I will take a try.
