### ISSUE TITLE
MomentumBatchNorm2d/1d works in FP16?

### ISSUE THREAD

**Issue by guanfuchen** [zengarden/momentum2-teacher#2]
Does this implementation of MomentumBatchNorm2d/1d work in mixed precision using FP16?

**Comment by zengarden** [comment]
You may need to do some manual processing in momentum bn `forward`,

```
def forward(self, x):
    HALF = False
    if x.type() == 'torch.cuda.HalfTensor':
        HALF = True
        x = x.float()
    
    execute_the_original_forward_codes_hear
    
    if HALF:
        out = out.half()
```

**Comment by guanfuchen** [comment]
It is compatiable with apex, and the accuracy is same with FP16. I try to use MomentumBN to replace SyncBN, the linear acc is nearly same and transfer acc is almost same for 4096 bz traning. Does this mean the MomentumBN can be used in small batch size and do not harm in large batch size?

**Comment by zengarden** [comment]
Yes, in my experiments, Momentum BN achieves on par or even better performances than SyncBN. Especially in the small batch training, the accuracy can be significantly improved.   And it's also faster.  Noticing currently, Momentum Bn is only applicable to the teacher network.
