### ISSUE TITLE
Teacher network weights used for linear evaluation

### ISSUE THREAD

**Issue by oliviermoliner** [zengarden/momentum2-teacher#4]
Hi, and thanks a lot for sharing your code!
I noticed that both MoCo and BYOL use the frozen weights from the student network for linear evaluation, whereas your evaluation script uses the weights from the teacher network.

In my tests (on another dataset) the linear evaluation score is much better when using the student network weights. Could you confirm which weights were used in the paper?

**Comment by zengarden** [comment]
*I* use weights of the teacher in the paper.

Olivier Moliner <notifications@github.com> 于2021年2月24日周三 下午10:08写道：

**Comment by oliviermoliner** [comment]
Thanks for your response!
